# Copyright (C) 2006  Adam Charrett

# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA

# msgcodes.py

# Binary Communications protocol message codes.

# (AUTOGENERATED Fri Jul 28 17:01:26 GMTST 2006)

#Start of RERR codes
RERR_OK            = 0x00 # Success
RERR_NOTAUTHORISED = 0x01 # Not authorised
RERR_EXISTS        = 0x02 # Output Already Exists
RERR_NOTFOUND      = 0x03 # Not found
RERR_STREAMING     = 0x04 # Already streaming to requested ip:port
RERR_GENERIC       = 0xFF # Generic Error (see message)
# End of RERR codes

#Start of INFO codes
INFO_NAME          = 0x00 # Name (user defined) of this server
INFO_FETYPE        = 0x01 # Front End Type
INFO_AUTHENTICATED = 0x02 # Is connection authenticated 
INFO_UPSECS        = 0xFE # Uptime string in seconds ie "61" 
INFO_UPTIME        = 0xFF # Uptime string "%d days %d hours %d minutes %d seconds"
# End of INFO codes

#Start of MSGCODE codes
MSGCODE_INFO = 0x0000 # Information message
MSGCODE_AUTH = 0x0001 # Authenticate
MSGCODE_QUOT = 0x0002 # Quote command
MSGCODE_CSPS = 0x1101 # Control Service Primary Select - Select Primary Service
MSGCODE_CSSA = 0x1102 # Control Service Secondary Add - Add secondary service
MSGCODE_CSSS = 0x1103 # Control Service Secondary Select - Select a secondary service
MSGCODE_CSSR = 0x1104 # Control Service Secondary Remove - Remove secondary service
MSGCODE_COAO = 0x1201 # Control Output Add Output - Add a new output destination
MSGCODE_CORO = 0x1202 # Control Output Remove Output - Remove an output destination
MSGCODE_COAP = 0x1203 # Control Output Add PIDs - Add pids to an output.
MSGCODE_CORP = 0x1204 # Control Output remove PIDs - Remove pids from an output.
MSGCODE_SSPS = 0x2101 # Status Service Primary Service - Return current service name for primary service output.
MSGCODE_SSFL = 0x2102 # Status Service Filter List - List service filters outputs.
MSGCODE_SSPC = 0x2103 # Status Service Packet Count
MSGCODE_SOLO = 0x2201 # Status Outputs List outputs
MSGCODE_SOLP = 0x2202 # Status Output List pids
MSGCODE_SOPC = 0x2203 # Status Output Packet Count
MSGCODE_STSS = 0x2F01 # Status TS Stats
MSGCODE_SFES = 0x2F02 # Status Front End Status
MSGCODE_SSLA = 0x2F03 # Status Services List All - List all avaialable services
MSGCODE_SSLM = 0x2F04 # Status Services List Multiplex - List services avaialable of the current multiplex
MSGCODE_SSPL = 0x2F05 # Status Services List PIDs
MSGCODE_RSSL = 0xF001 # Response Service Secondary List
MSGCODE_ROLO = 0xF002 # Response Outputs List outputs
MSGCODE_RLP  = 0xF003 # Response Output List pids
MSGCODE_ROPC = 0xF004 # Response Output Packet Count
MSGCODE_RTSS = 0xF005 # Response TS Stats
MSGCODE_RFES = 0xF006 # Response Front End Status
MSGCODE_RLS  = 0xF007 # Response Services List
MSGCODE_RTXT = 0xF008 # Response Text
MSGCODE_RERR = 0xFFFF # Response Error
# End of MSGCODE codes

